version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Setting up virtual environment..."
      - python -m venv .venv
      - source .venv/bin/activate
      - python -m pip install --upgrade pip
  build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - echo "Running tests..."
      - pytest --junitxml=reports/test-results.xml || exit 1

artifacts:
  files:
    - reports/test-results.xml

cache:
  paths:
    - /root/.cache/pip