version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip
      # Conditionally install dependencies based on platform
      - if [ "$(uname)" != "Linux" ]; then
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi;
        else
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt --no-deps;
          fi;
        fi

  build:
    commands:
      - echo "Running tests..."
      - mkdir -p reports
      # Run tests and generate XML report
      - pytest tests/ --junitxml=reports/test-results.xml -v

artifacts:
  files:
    # Include the test results and all other necessary files
    - 'reports/test-results.xml'
    - '**/*'

reports:
  pytest_reports:
    files:
      - 'reports/test-results.xml'
    base-directory: reports
