version: 0.2

phases:
  install:
    # Step 1: Specify the Python version and install pip dependencies
    runtime-versions:
      python: 3.10
    commands:
      - pip install --upgrade pip  # Ensure pip is the latest version
      - pip install -r requirements.txt  # Install all the dependencies

  build:
    # Step 2: Run tests using pytest
    commands:
      - pytest --junitxml=test-results.xml  # Run tests and generate a report

artifacts:
  # Step 3: Save the test results as artifacts
  files:
    - test-results.xml
