version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip
      - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  build:
    commands:
      - echo "Running tests..."
      - pytest tests/ --junitxml=reports/test-results.xml || exit 1

artifacts:
  files:
    - '**/*'
reports:
  pytest_reports:
    files:
      - '**/test-results.xml'
    base-directory: reports
