version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing Python dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - pytest --junitxml=reports/test-results.xml  # Save test results in a specific directory for artifacts

artifacts:
  files:
    - reports/test-results.xml  # Ensure artifacts refer to the correct path
  discard-paths: no             # Preserve directory structure for better organization